orders_tracker/blueprints/orders/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from orders_tracker.blueprints.orders.service import add_order, get_orders_count, get_form_fields, get_path_args, \
    filter_orders, \
    render_empty, paginate_orders, get_pagination_metadata, update_order, change_order_status
from orders_tracker.forms import NewOrderForm, NavigationForm, CancelConfirmForm
from orders_tracker.models import Order, Staff
from orders_tracker.tables import OrdersTable

orders_blueprint = Blueprint('orders_bp', __name__, template_folder="templates")


@orders_blueprint.route('/orders/new', methods=['GET', 'POST'])
def new_order():
    choices = Staff.query.all()
    form = NewOrderForm(formdata=request.form, staff_choices=choices)
    if request.method == 'POST':
        if form.validate_on_submit():
            return_code = add_order(form)
            if return_code == 0:
                return redirect(url_for('orders_bp.orders'))
        else:
            flash('Перевірте введені значення.', category='warning')

    return render_template('new_order.html', form=form)


@orders_blueprint.route('/orders', methods=['GET', 'POST'])
def orders():
    if request.method == 'POST':
        sort_by_field, status_field, search_field = get_form_fields()
        return redirect(url_for('orders_bp.orders',
                                sort_by=sort_by_field,
                                status=status_field,
                                search_query=search_field))

    search_arg, sort_by_arg, status_arg, page_arg = get_path_args()

    stats = {'total': get_orders_count(), 'filter': -1}

    orders_query = filter_orders(search_arg, sort_by_arg, status_arg)

    navigation_form = NavigationForm(search_field=search_arg,
                                     sort_by_field=sort_by_arg,
                                     status_field=status_arg)

    stats['filter'] = orders_query.count()
    if stats['filter'] == 0:
        return render_empty(stats, navigation_form)

    pagination_metadata = get_pagination_metadata(page_arg, orders_query)
    orders_list = paginate_orders(pagination_metadata, orders_query)
    table = OrdersTable(orders_list)

    return render_template('orders.html',
                           table=table,
                           stats=stats,
                           pagination_data=pagination_metadata,
                           navigation_form=navigation_form)


@orders_blueprint.route('/orders/<order_id>', methods=['GET', 'POST'])
def order(order_id):
    selected_order = Order.query.filter_by(id=order_id).first_or_404()

    if request.method == 'POST':
        if request.form.get('start'):
            selected_order.status_id = 2
        elif request.form.get('finish'):
            selected_order.status_id = 3

        change_order_status(selected_order)
        return redirect(url_for('orders_bp.order', order_id=selected_order.id))

    return render_template('order.html', order=selected_order)


@orders_blueprint.route('/orders/<order_id>/edit', methods=['GET', 'POST'])
def edit_order(order_id):
    choices = Staff.query.all()
    edited_order = Order.query.filter_by(id=order_id).first()
    modal_form = NewOrderForm(staff_choices=choices)

    if request.method == 'POST':
        if modal_form.validate_on_submit():
            update_order(modal_form, order_id)
            return redirect(url_for('orders_bp.order', order_id=edited_order.id))
        else:
            flash('Дані про замовлення не оновлено.', category='warning')

    modal_form = NewOrderForm(order=edited_order, staff_choices=choices)

    return render_template('edit_order.html',
                           form=modal_form,
                           message_title="Редагування інформації про замовлення",
                           order_id=edited_order.id)


@orders_blueprint.route('/orders/<order_id>/cancel', methods=['GET', 'POST'])
def cancel_order(order_id):
    selected_order = Order.query.filter_by(id=order_id).first_or_404()
    form = CancelConfirmForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            selected_order.status_id = 4
            change_order_status(selected_order)
            return redirect(url_for('orders_bp.order', order_id=selected_order.id))

    return render_template('cancel_confirm.html',
                           form=form,
                           order_id=selected_order.id,
                           message_title="Скасування замовлення",
                           message="Ви дійсно бажаєте скасувати замовлення №" + str(selected_order.id) + "?")

orders_tracker/blueprints/orders/templates/edit_order.html
{% extends 'modal.html' %}

{% set return_link=url_for('orders_bp.order', order_id=order_id) %}


{% block message_header %}
    <div class="level-item">
        <p id="message_title">{{ message_title }}</p>
    </div>
    <div class="level-item is-hidden-mobile">
        <ion-icon size="large" name="create-outline"></ion-icon>
    </div>
{% endblock %}

{% block form %}
    {% if get_flashed_messages(with_categories=True) %}
        {% include 'notification.html' %}
    {% endif %}

    <form action="" method="post" id="new_order_form">
        {{ form.hidden_tag() }}
        <div class="field is-horizontal">
            <div class="column">
                <div class="field">
                    <label class="label">{{ form.title.label }}</label>
                    <p class="control is-expanded">
                        {{ form.title(class='input') }}
                    </p>
                </div>
                <div class="field">
                    <label class="label">{{ form.price.label }}</label>
                    <div class="field-body">
                        <div class="field is-expanded">
                            <div class="field has-addons">
                                <p class="control is-expanded has-icons-left">
                                    {{ form.price(class='input') }}
                                    <span class="icon is-left">
                                                    <ion-icon name="cash-outline"></ion-icon>
                                                </span>
                                </p>
                                <p class="control">
                                    <a class="button is-link is-static">
                                        UAH
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <label class="label">{{ form.staff.label }}</label>
                    <div class="control is-expanded has-icons-left">
                        <div class="select is-fullwidth">
                                        <span class="icon is-left">
                                            <ion-icon name="person-outline"></ion-icon>
                                        </span>
                            {{ form.staff(class="is-fullwidth") }}
                        </div>
                    </div>
                </div>
            </div>

            <div class="column">
                <div class="field">
                    <label class="label">{{ form.client.label }}</label>
                    <div class="control is-expanded has-icons-left">
                        {{ form.client(class='input') }}
                        <span class="icon is-left">
                            <ion-icon name="business"></ion-icon>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label">{{ form.serial.label }}</label>
                    <p class="control is-expanded">
                        {{ form.serial(class='input') }}
                    </p>
                </div>
                {{ datepicker.loader(theme="base") }} {# to load jQuery-ui #}
                {{ datepicker.picker(id=".dp") }}
                <div class="field">
                    <label class="label">{{ form.created_at.label }}</label>
                    <div class="control is-expanded has-icons-left">
                        {{ form.created_at(class='input dp') }}
                        <span class="icon is-left">
                            <ion-icon name="calendar-outline"></ion-icon>
                        </span>
                    </div>
                </div>
            </div>

            <div class="column is-fullheight">
                <label class="label">{{ form.description.label }}</label>
                <div class="control is-expanded">
                    {{ form.description(class='textarea', rows="7") }}
                </div>
            </div>
        </div>
        <br/>
        <br/>
        <div class="columns is-centered">
            <div class="column is-3">
                <div class="control has-icon-right">
                    {{ form.submit(class='button is-link is-light is-rounded is-fullwidth') }}
                </div>
            </div>
        </div>

    </form>

    <script>
        $(function () {
            $.ajax({
                url: '{{ url_for("api_bp.client_autocomplete") }}'
            }).done(function (data) {
                $('#client_autocomplete').autocomplete({
                    classes: {"ui-autocomplete": "highlight"},
                    source: data
                });
            });
        });

        $(function () {
            $.ajax({
                url: '/api/autocomplete/devices?client_name=' + $('#client_autocomplete').val()
            }).done(function (data) {
                $('#serial_autocomplete').autocomplete({
                    classes: {"ui-autocomplete": "highlight"},
                    source: data
                });
            });
        });

        $(document).ready(function () {
            $('#client_autocomplete').change(function () {
                $.ajax({
                    url: '/api/autocomplete/devices?client_name=' + $('#client_autocomplete').val()
                }).done(function (data) {
                    $('#serial_autocomplete').autocomplete({
                        classes: {"ui-autocomplete": "highlight"},
                        source: data
                    });
                });
            });
        });

        $('.dp').datepicker({
            dateFormat: "dd.mm.yy",
            monthNames: ['Січень', 'Лютий', 'Березень', 'Квітень', 'Травень', 'Червень', 'Липень', 'Серпень', 'Вересень', 'Жовтень', 'Листопад', 'Грудень'],
            dayNamesMin: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            firstDay: 1
        });
    </script>
{% endblock %}

orders_tracker/blueprints/orders/templates/new_order.html
{% extends "message.html" %}

{% block panel %}
    {% if get_flashed_messages(with_categories=True) %}
        {% include 'notification.html' %}
    {% else %}
        <div class="level">
        </div>
    {% endif %}
{% endblock %}

{% block message_color %}
    is-dark
{% endblock %}

{% block breadcrumbs %}
    <nav class="breadcrumb pl-3">
        <ul>
            <li class="is-active">
                <a>
                    <ion-icon name="bag-outline"></ion-icon>
                    <span class="pl-2">Замовлення</span>
                </a>
            </li>
            <li>
                <a href="">
                    <ion-icon name="bag-add-outline"></ion-icon>
                    <span class="pl-2">Додати нове</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block message_header %}
    <ion-icon size="large" name="bag-add-outline"></ion-icon>
    <span class="pl-2">Нове замовлення</span>
{% endblock %}

{% block message_body %}
    <form action="" method="post" id="new_order_form">
        {{ form.hidden_tag() }}
        <div class="field is-horizontal">
            <div class="column">
                <div class="field">
                    <label class="label">{{ form.title.label }}</label>
                    <p class="control is-expanded">
                        {{ form.title(class='input') }}
                    </p>
                </div>
                <div class="field">
                    <label class="label">{{ form.price.label }}</label>
                    <div class="field-body">
                        <div class="field is-expanded">
                            <div class="field has-addons">
                                <p class="control is-expanded has-icons-left">
                                    {{ form.price(class='input') }}
                                    <span class="icon is-left">
                                                    <ion-icon name="cash-outline"></ion-icon>
                                                </span>
                                </p>
                                <p class="control">
                                    <a class="button is-link is-static">
                                        UAH
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <label class="label">{{ form.staff.label }}</label>
                    <div class="control is-expanded has-icons-left">
                        <div class="select is-fullwidth">
                                        <span class="icon is-left">
                                            <ion-icon name="person-outline"></ion-icon>
                                        </span>
                            {{ form.staff(class="is-fullwidth") }}
                        </div>
                    </div>
                </div>
            </div>

            <div class="column">
                <div class="field">
                    <label class="label">{{ form.client.label }}</label>
                    <div class="control is-expanded has-icons-left">
                        {{ form.client(class='input') }}
                        <span class="icon is-left">
                            <ion-icon name="business"></ion-icon>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label">{{ form.serial.label }}</label>
                    <p class="control is-expanded">
                        {{ form.serial(class='input') }}
                    </p>
                </div>
                {{ datepicker.loader(theme="base") }} {# to load jQuery-ui #}
                {{ datepicker.picker(id=".dp") }}
                <div class="field">
                    <label class="label">{{ form.date.label }}</label>
                    <div class="control is-expanded has-icons-left">
                        {{ form.date(class='input dp') }}
                        <span class="icon is-left">
                            <ion-icon name="calendar-outline"></ion-icon>
                        </span>
                    </div>
                </div>
            </div>

            <div class="column is-fullheight">
                <label class="label">{{ form.description.label }}</label>
                <div class="control is-expanded">
                    {{ form.description(class='textarea', rows="7") }}
                </div>
            </div>
        </div>
        <br/>
        <br/>
        <div class="columns is-centered">
            <div class="column is-3">
                <div class="control has-icon-right">
                    {{ form.submit(class='button is-link is-light is-rounded is-fullwidth') }}
                </div>
            </div>
        </div>

    </form>

    <script>
        $(function () {
            $.ajax({
                url: '{{ url_for("api_bp.title_autocomplete") }}'
            }).done(function (data) {
                $('#title_autocomplete').autocomplete({
                    classes: {"ui-autocomplete": "highlight"},
                    source: data,
                    minLength: 0
                }).focus(function () {
                    $(this).autocomplete('search', $(this).val());
                });
            });
        });


        $(function () {
            $.ajax({
                url: '{{ url_for("api_bp.client_autocomplete") }}'
            }).done(function (data) {
                $('#client_autocomplete').autocomplete({
                    classes: {"ui-autocomplete": "highlight"},
                    source: data,
                    minLength: 0,
                    change: autoCompleteChanged
                }).focus(function () {
                    $(this).autocomplete('search', $(this).val());
                });
            });
        });

        function autoCompleteChanged(event, ui) {
            $.ajax({
                    url: '/api/autocomplete/devices?client_name=' + $('#client_autocomplete').val()
                }).done(function (data) {
                    $('#serial_autocomplete').autocomplete({
                        classes: {"ui-autocomplete": "highlight"},
                        source: data,
                        minLength: 0
                    }).focus(function () {
                        $(this).autocomplete('search', $(this).val());
                    });
                }).fail(function () {
                    $('#serial_autocomplete').autocomplete({
                        classes: {"ui-autocomplete": "highlight"},
                        source: null,
                        minLength: 0
                    }).focus(function () {
                        $(this).autocomplete('search', $(this).val());
                    });
                });
        }

        {#$(function () {#}
        {#    $.ajax({#}
        {#        url: '{{ url_for("api_bp.staff_autocomplete") }}'#}
        {#    }).done(function (data) {#}
        {#        $('#staff_autocomplete').autocomplete({#}
        {#            classes: {"ui-autocomplete": "highlight"},#}
        {#            source: data#}
        {#        });#}
        {#    });#}


        $('.dp').datepicker({
            dateFormat: "dd.mm.yy",
            monthNames: ['Січень', 'Лютий', 'Березень', 'Квітень', 'Травень', 'Червень', 'Липень', 'Серпень', 'Вересень', 'Жовтень', 'Листопад', 'Грудень'],
            dayNamesMin: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            firstDay: 1
        });
    </script>
{% endblock %}

orders_tracker/blueprints/orders/templates/order.html
{% extends "message.html" %}

{% block panel %}
    {% if get_flashed_messages(with_categories=True) %}
        {% include 'notification.html' %}
    {% else %}
        <div class="section"></div>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <nav class="breadcrumb pl-3">
        <ul>
            <li class="is-active">
                <a>
                    <ion-icon name="bag-outline"></ion-icon>
                    <span class="pl-2">Замовлення</span>
                </a>
            </li>
            <li>
                <a href="{{ url_for("orders_bp.orders") }}">
                    <ion-icon name="list-outline"></ion-icon>
                    <span class="pl-2">Всі</span>
                </a>
            </li>
            <li>
                <a href="">
                    <ion-icon name="information-outline"></ion-icon>
                    <span class="pl-2">Інформація про №{{ order.id }}</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block message_header %}
    <ion-icon size="large" name="information-circle-outline"></ion-icon>
    <span class="pl-2">Деталі замовлення</span>
{% endblock %}

{% block message_body %}
    <div class="box">
        <div class="level">
            <div class="level-left">
                <ion-icon size="large" name="attach-outline"></ion-icon>
                <span class="title has-text-weight-light is-4">Замовлення
                    <span class="has-text-weight-bold is-italic">№ {{ order.id }}</span>
                </span>
            </div>

            <div class="level-right has-text-right is-unselectable">
                {% if order.status_id == 1 %}
                    <span class="tag is-medium is-link">
                        {{ order.status }}
                        <ion-icon class="pl-2" name="bulb"></ion-icon>
                    </span>
                {% elif order.status_id == 2 %}
                    <span class="tag is-medium is-warning">
                        {{ order.status }}
                        <ion-icon class="pl-2" name="cog"></ion-icon>
                    </span>
                {% elif order.status_id == 3 %}
                    <span class="tag is-medium is-success">
                        {{ order.status }}
                        <ion-icon class="pl-2" name="checkmark-circle"></ion-icon>
                    </span>
                {% elif order.status_id == 4 %}
                    <span class="tag is-medium is-danger">
                        {{ order.status }}
                        <ion-icon class="pl-2" name="close-circle"></ion-icon>
                    </span>
                {% endif %}
            </div>
        </div>
        <hr/>

        <div class="columns mt-5">
            <div class="column">
                <div class="container is-fluid ml-5">
                    <h5 class="title is-5">{{ order.title }}</h5>
                    <div class="block">Пристрій:
                        <strong>{{ order.device.name if order.device.name else "(Без назви)" }}</strong>
                        <span class="tag is-primary is-light is-rounded">
                                    <strong>{{ order.device.serial }}</strong>
                        </span>
                    </div>
                    <div class="block">Клієнт:
                        <a href="{{ url_for("clients_bp.client", client_id=order.client.id) }}">
                            <strong>{{ order.client }}</strong>
                        </a>
                    </div>
                    <div class="block">Вартість:
                        <strong>{{ order.price if order.price else "(Не вказано)" }} грн</strong>
                    </div>
                    <div class="block">Виконавець:
                        <strong>{{ order.staff.name if order.staff.name else "(Не вказано)" }}</strong>
                    </div>
                </div>

            </div>
            <div class="column">
                {% if order.description %}
                    <h5 class="subtitle is-5">Опис:</h5>
                    <li><strong>{{ order.description }}</strong></li>
                {% endif %}
            </div>
        </div>
        <div class="block has-text-right">
            <span class="heading is-size-7">Додано: {{ order.created_at.strftime('%d.%m.%Y') }}</span>
        </div>
        <hr>
        <div class="level">
            <div class="level-left pl-4">
                <a class="button is-rounded is-link is-outlined"
                   href="{{ url_for('orders_bp.edit_order', order_id=order.id) }}">
                    <span>Редагувати</span>
                    <span class="icon"><ion-icon name="pencil-outline"></ion-icon></span>
                </a>
            </div>

            <div class="level-right">
                <form action="" method="post">
                    {% if order.status_id == 1 %}
                        <input class="button is-rounded is-light is-link" type="submit" name="start"
                               value="Розпочати"/>
                    {% elif order.status_id == 2 %}
                        <input class="button is-rounded is-light is-success" type="submit" name="finish"
                               value="Завершити"/>
                    {% endif %}
                    {% if order.status_id < 3 %}
                        <a class="button is-rounded is-danger is-light"
                           href="{{ url_for('orders_bp.cancel_order', order_id=order.id) }}">
                            <span>Скасувати</span>
                        </a>
                    {% endif %}
                </form>
            </div>
        </div>

    </div>
{% endblock %}