orders_tracker/blueprints/clients/routes.py
import urllib

from flask import Blueprint, request, render_template, flash, redirect, url_for

from orders_tracker.blueprints.clients.service import add_client, update_client, remove_client, search_clients, \
    get_form_fields, get_path_args, \
    get_clients_count, render_empty, get_pagination_metadata, paginate_clients
from orders_tracker.forms import NewClientForm, DeleteConfirmForm
from orders_tracker.models import Client, Device
from orders_tracker.tables import ClientsTable

clients_blueprint = Blueprint('clients_bp', __name__, template_folder="templates")


@clients_blueprint.route('/clients/new', methods=['GET', 'POST'])
def new_client():
    form = NewClientForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            created_client = Client(form.name.data, form.phone.data, form.address.data, form.notes.data)
            add_client(created_client)
            return redirect(url_for('clients_bp.clients'))
        else:
            flash('Перевірте введені значення.', category='warning')

    return render_template('new_client.html', form=form)


@clients_blueprint.route('/clients', methods=['GET', 'POST'])
def clients():
    if request.method == 'POST':
        search_field = get_form_fields()
        return redirect(url_for('clients_bp.clients',
                                search_query=search_field))

    search_arg, page_arg = get_path_args()

    stats = {'total': get_clients_count(), 'filter': -1}

    clients_query = search_clients(search_arg)

    stats['filter'] = clients_query.count()
    if stats['filter'] == 0:
        return render_empty(stats, search_arg)

    pagination_metadata = get_pagination_metadata(page_arg, clients_query)

    clients_list = paginate_clients(pagination_metadata, clients_query)
    table = ClientsTable(clients_list)

    return render_template('clients.html',
                           table=table,
                           stats=stats,
                           search_field_value=search_arg,
                           pagination_data=pagination_metadata)


@clients_blueprint.route('/clients/<client_id>', methods=['GET', 'POST'])
def client(client_id):
    address_link = None
    selected_client = Client.query.filter_by(id=client_id).first_or_404()
    if selected_client.address:
        address_link = "https://www.google.com/maps/search/?api=1&query=" + \
                       urllib.parse.quote_plus(selected_client.address)

    devices = Device.query.filter_by(client_id=client_id).all()

    return render_template('client.html',
                           client=selected_client,
                           devices=devices,
                           address_link=address_link)


@clients_blueprint.route('/clients/<client_id>/edit', methods=['GET', 'POST'])
def edit_client(client_id):
    edited_client = Client.query.filter_by(id=client_id).first()
    modal_form = NewClientForm()

    if request.method == 'POST':
        if modal_form.validate_on_submit():
            edited_client.name = modal_form.name.data.strip()
            edited_client.phone = modal_form.phone.data
            edited_client.address = modal_form.address.data
            edited_client.notes = modal_form.notes.data
            update_client(edited_client)
            return redirect(url_for('clients_bp.client', client_id=edited_client.id))
        else:
            flash('Дані про клієнта не оновлено.', category='warning')

    modal_form = NewClientForm(edited_client)
    return render_template('edit_client.html',
                           form=modal_form,
                           message_title="Редагування інформації про клієнта",
                           client_id=edited_client.id,
                           color="is-link")


@clients_blueprint.route('/clients/<client_id>/delete', methods=['GET', 'POST'])
def delete_client(client_id):
    deleted_client = Client.query.filter_by(id=client_id).first()
    form = DeleteConfirmForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            remove_client(deleted_client)
            return redirect(url_for('clients_bp.clients'))

    return render_template('delete_confirm.html',
                           form=form,
                           client_id=deleted_client.id,
                           message_title="Видалення клієнта",
                           message="Ви дійсно бажаєте видалити клієнта " + deleted_client.name + "?")

orders_tracker/blueprints/orders/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from orders_tracker.blueprints.orders.service import add_order, get_orders_count, get_form_fields, get_path_args, \
    filter_orders, \
    render_empty, paginate_orders, get_pagination_metadata, update_order, change_order_status
from orders_tracker.forms import NewOrderForm, NavigationForm, CancelConfirmForm
from orders_tracker.models import Order, Staff
from orders_tracker.tables import OrdersTable

orders_blueprint = Blueprint('orders_bp', __name__, template_folder="templates")


@orders_blueprint.route('/orders/new', methods=['GET', 'POST'])
def new_order():
    choices = Staff.query.all()
    form = NewOrderForm(formdata=request.form, staff_choices=choices)
    if request.method == 'POST':
        if form.validate_on_submit():
            return_code = add_order(form)
            if return_code == 0:
                return redirect(url_for('orders_bp.orders'))
        else:
            flash('Перевірте введені значення.', category='warning')

    return render_template('new_order.html', form=form)


@orders_blueprint.route('/orders', methods=['GET', 'POST'])
def orders():
    if request.method == 'POST':
        sort_by_field, status_field, search_field = get_form_fields()
        return redirect(url_for('orders_bp.orders',
                                sort_by=sort_by_field,
                                status=status_field,
                                search_query=search_field))

    search_arg, sort_by_arg, status_arg, page_arg = get_path_args()

    stats = {'total': get_orders_count(), 'filter': -1}

    orders_query = filter_orders(search_arg, sort_by_arg, status_arg)

    navigation_form = NavigationForm(search_field=search_arg,
                                     sort_by_field=sort_by_arg,
                                     status_field=status_arg)

    stats['filter'] = orders_query.count()
    if stats['filter'] == 0:
        return render_empty(stats, navigation_form)

    pagination_metadata = get_pagination_metadata(page_arg, orders_query)
    orders_list = paginate_orders(pagination_metadata, orders_query)
    table = OrdersTable(orders_list)

    return render_template('orders.html',
                           table=table,
                           stats=stats,
                           pagination_data=pagination_metadata,
                           navigation_form=navigation_form)


@orders_blueprint.route('/orders/<order_id>', methods=['GET', 'POST'])
def order(order_id):
    selected_order = Order.query.filter_by(id=order_id).first_or_404()

    if request.method == 'POST':
        if request.form.get('start'):
            selected_order.status_id = 2
        elif request.form.get('finish'):
            selected_order.status_id = 3

        change_order_status(selected_order)
        return redirect(url_for('orders_bp.order', order_id=selected_order.id))

    return render_template('order.html', order=selected_order)


@orders_blueprint.route('/orders/<order_id>/edit', methods=['GET', 'POST'])
def edit_order(order_id):
    choices = Staff.query.all()
    edited_order = Order.query.filter_by(id=order_id).first()
    modal_form = NewOrderForm(staff_choices=choices)

    if request.method == 'POST':
        if modal_form.validate_on_submit():
            update_order(modal_form, order_id)
            return redirect(url_for('orders_bp.order', order_id=edited_order.id))
        else:
            flash('Дані про замовлення не оновлено.', category='warning')

    modal_form = NewOrderForm(order=edited_order, staff_choices=choices)

    return render_template('edit_order.html',
                           form=modal_form,
                           message_title="Редагування інформації про замовлення",
                           order_id=edited_order.id)


@orders_blueprint.route('/orders/<order_id>/cancel', methods=['GET', 'POST'])
def cancel_order(order_id):
    selected_order = Order.query.filter_by(id=order_id).first_or_404()
    form = CancelConfirmForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            selected_order.status_id = 4
            change_order_status(selected_order)
            return redirect(url_for('orders_bp.order', order_id=selected_order.id))

    return render_template('cancel_confirm.html',
                           form=form,
                           order_id=selected_order.id,
                           message_title="Скасування замовлення",
                           message="Ви дійсно бажаєте скасувати замовлення №" + str(selected_order.id) + "?")

orders_tracker/blueprints/start/routes.py
from flask import Blueprint, render_template

start_blueprint = Blueprint('start_bp', __name__, template_folder="templates")


@start_blueprint.route('/start', methods=['GET'])
def start():
    return render_template('start_base.html')

orders_tracker/templates/base.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Трекер_Замовлень</title>

    <link rel="stylesheet" href="/static/css/bulma.min.css"/>
    <link rel="stylesheet" href="/static/css/style.css"/>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/icon.png') }}">

    <script src="/static/ionicons/ionicons.esm.js" type="module"></script>
    <script nomodule src="/static/ionicons/ionicons.esm.js"></script>

    <link rel="stylesheet" href="/static/jquery/jquery-ui.css">
    <script type="text/javascript" src="/static/jquery/jquery-latest.js"></script>
    <script src="/static/jquery/jquery-ui.js"></script>

</head>

<body>
<section class="container is-fluid" id="hero">
    <nav class="section">
        <div class="level">
            <div class="level-left">
                <div class="level-item">
                    <a href="{{ url_for('orders_bp.orders') }}">
                        <img src="/static/img/icon.png" width="64" height="64" alt="icon">
                    </a>
                </div>
                <div class="level-item has-text-centered">
                        <span class="title is-4">
                            <span class="title is-4 has-text-link">Трекер</span>_Замовлень
                        </span>
                </div>
            </div>
            <div class="level-right">
                <div class="level-item">
                    <a href="{{ url_for('orders_bp.new_order') }}" class="navbar-item title is-6">
                        <div class="level">
                            <ion-icon size="large" name="bag-add-outline"></ion-icon>
                            <span class="is-hidden-mobile" style="margin-left: 10px">Нове замовлення</span>
                        </div>
                    </a>
                </div>
                <div class="level-item">
                    <a href="{{ url_for('clients_bp.new_client') }}" class="navbar-item title is-6">
                        <div class="level">
                            <ion-icon size="large" name="person-add-outline"></ion-icon>
                            <span class="is-hidden-mobile" style="margin-left: 10px">Новий клієнт</span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </nav>

    {% block panel %}
    {% endblock %}

    <div id="workspace">
        {% block breadcrumbs %}
        {% endblock %}
        <div class="columns">
            <div class="column">
                {% block content %}
                {% endblock %}
            </div>

            {% block side_menu %}
                <div class="column is-one-fifth">
                    <div class="box">
                        <aside class="menu">
                            <div class="block">
                                <div class="level-left">
                                    <ion-icon class="has-text-link" size="large" name="bag-outline"></ion-icon>
                                    <span class="subtitle pl-2">Замовлення</span>
                                </div>
                                <br/>
                                <ul class="menu-list">
                                    <li>
                                        <a href="{{ url_for('orders_bp.orders', status=1) }}"
                                           class="navbar-item title is-6">
                                            <div class="level-left">
                                                <ion-icon name="bulb-outline"></ion-icon>
                                                <span class="pl-2">Нові</span>
                                            </div>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="{{ url_for('orders_bp.orders', status=2) }}"
                                           class="navbar-item title is-6">
                                            <div class="level-left">
                                                <ion-icon name="cog-outline"></ion-icon>
                                                <span class="pl-2">В процесі</span>
                                            </div>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="{{ url_for('orders_bp.orders', search_query=week) }}"
                                           class="navbar-item title is-6">
                                            <div class="level-left">
                                                <ion-icon name="calendar-outline"></ion-icon>
                                                <span class="pl-2">За останні 7 днів</span>
                                            </div>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="{{ url_for('orders_bp.orders', search_query=month) }}"
                                           class="navbar-item title is-6">
                                            <div class="level-left">
                                                <ion-icon name="calendar-outline"></ion-icon>
                                                <span class="pl-2">За останні 30 днів</span>
                                            </div>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="{{ url_for('orders_bp.orders', type=1) }}"
                                           class="navbar-item title is-6">
                                            <div class="level-left">
                                                <ion-icon name="funnel-outline"></ion-icon>
                                                <span class="pl-2">Заправки</span>
                                            </div>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="{{ url_for('orders_bp.orders') }}" class="navbar-item title is-6">
                                            <div class="level-left">
                                                <ion-icon name="list-outline"></ion-icon>
                                                <span class="pl-2">Всі замовлення</span>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                            <div class="block">
                                <div class="level-left">
                                    <ion-icon class="has-text-info" size="large" name="people-outline"></ion-icon>
                                    <span class="subtitle pl-2">Робота з клієнтами</span>
                                </div>
                                <br/>
                                <ul class="menu-list">
                                    <li>
                                        <a href="{{ url_for('clients_bp.clients') }}"
                                           class="title is-6"
                                           onMouseOver="this.style.color='#3298dc'"
                                           onMouseOut="this.style.color='#4a4a4a'">
                                            <div class="level-left">
                                                <ion-icon name="list-outline"></ion-icon>
                                                <span class="pl-2">Всі клієнти</span>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                            <div class="block">
                                <div class="level-left">
                                    <ion-icon class="has-text-primary-dark" size="large"
                                              name="happy-outline"></ion-icon>
                                    <span class="subtitle pl-2">Працівники</span>
                                </div>
                                <br/>
                                <ul class="menu-list">
                                    <li>
                                        <a href="{{ url_for('staff_bp.staff') }}"
                                           class="title is-6"
                                           onMouseOver="this.style.color='#339A84'"
                                           onMouseOut="this.style.color='#4a4a4a'">
                                            <div class="level-left">
                                                <ion-icon name="list-outline"></ion-icon>
                                                <span class="pl-2">Список працівників</span>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                            <hr/>

                            <div class="block">
                                <ul class="menu-list">
                                    <li>
                                        <a href="{{ url_for('start_bp.start') }}"
                                           class="title is-6">
                                            <div class="level-left">
                                                <ion-icon name="help-circle-outline"></ion-icon>
                                                <span class="pl-2">Допомога</span>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </aside>
                    </div>
                </div>
            {% endblock %}
        </div>
    </div>

    <br/>
    <div class="level">
        <div class="level-left"></div>
        <p class="level-right">
            <a href="https://g.page/FOP_Savchuk?share">
                <span class="tag heading is-size-7">© ФОП Савчук</span>
            </a>
        </p>
    </div>
</section>
</body>
</html>

orders_tracker/templates/cancel_confirm.html
{% extends 'modal.html' %}

{% set return_link=url_for('orders_bp.order', order_id=order_id) %}
{% set color='is-dark' %}

{% block message_header %}
    <div class="level-item">
        <p id="message_title">{{ message_title }}</p>
    </div>
    <div class="level-item is-hidden-mobile">
        <ion-icon size="large" name="close-outline"></ion-icon>
    </div>
{% endblock %}

{% block form %}
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div class="block ">
            <p class="subtitle is-5">{{ message }}</p>
        </div>
        <div class="block">
            <div class="field is-grouped">
                <div class="control">
                    {{ form.cancel(class='button is-danger is-outlined is-rounded') }}
                </div>
                <div class="control">
                    <a class="button is-link is-outlined is-rounded" href="{{ return_link }}">
                        Відміна
                    </a>
                </div>
            </div>
        </div>

    </form>
{% endblock %}

orders_tracker/templates/delete_confirm.html
{% extends 'modal.html' %}

{% set return_link=url_for('clients_bp.client', client_id=client_id) %}
{% set color='is-dark' %}

{% block message_header %}
    <div class="level-item">
        <p id="message_title">{{ message_title }}</p>
    </div>
    <div class="level-item is-hidden-mobile">
        <ion-icon size="large" name="trash-outline"></ion-icon>
    </div>
{% endblock %}

{% block form %}
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div class="block ">
            <p class="subtitle is-5">{{ message }}</p>
        </div>
        <div class="block">
            <div class="field is-grouped">
                <div class="control">
                    {{ form.delete(class='button is-danger is-outlined is-rounded') }}
                </div>
                <div class="control">
                    <a class="button is-link is-outlined is-rounded" href="{{ return_link }}">
                        Скасувати
                    </a>
                </div>
            </div>
        </div>

    </form>
{% endblock %}

orders_tracker/templates/message.html
{% extends "base.html" %}

{% block content %}
    <div class="message is-dark" id="card_shadow">
        <div class="message-header">
            <div class="level-left">
                {% block message_header %}
                {% endblock %}
            </div>
        </div>
        <div class="message-body">
            {% block message_body %}
            {% endblock %}
        </div>
    </div>

    {% block message_pagination %}
        {% if pagination_data %}
            <nav class="pagination is-right" role="navigation" aria-label="pagination">
                {% if pagination_data['current'] != 1 %}
                    <a class="pagination-previous"
                       href="{{ previous_link }}">
                        Попередня
                    </a>
                {% else %}
                    <button class="pagination-previous" disabled>
                        Попередня
                    </button>
                {% endif %}

                {% if pagination_data['current'] != pagination_data['last'] %}
                    <a class="pagination-next"
                       href="{{ next_link }}">
                        Наступна
                    </a>
                {% else %}
                    <button class="pagination-previous" disabled>
                        Наступна
                    </button>
                {% endif %}

                <ul class="pagination-list">
                    {% if pagination_data['current'] != pagination_data['first'] %}
                        <li>
                            <a class="pagination-link"
                               href="{{ first_link }}">
                                {{ pagination_data['first'] }}
                            </a>
                        </li>
                    {% endif %}

                    {% if pagination_data['previous'] - 1 > pagination_data['first'] %}
                        <li><span class="pagination-ellipsis">&hellip;</span></li>
                    {% endif %}

                    {% if pagination_data['previous'] > pagination_data['first'] %}
                        <li>
                            <a class="pagination-link"
                               href="{{ previous_link }}">
                                {{ pagination_data['previous'] }}
                            </a>
                        </li>
                    {% endif %}

                    <li>
                        <a class="pagination-link is-current"
                           href="{{ current_link }}">
                            {{ pagination_data['current'] }}
                        </a>
                    </li>

                    {% if pagination_data['next'] < pagination_data['last'] %}
                        <li>
                            <a class="pagination-link"
                               href="{{ next_link }}">
                                {{ pagination_data['next'] }}
                            </a>
                        </li>
                    {% endif %}

                    {% if pagination_data['next'] + 1 < pagination_data['last'] %}
                        <li><span class="pagination-ellipsis">&hellip;</span></li>
                    {% endif %}

                    {% if pagination_data['next'] <= pagination_data['last'] %}
                        <li>
                            <a class="pagination-link"
                               href="{{ last_link }}">
                                {{ pagination_data['last'] }}
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    {% endblock %}

{% endblock %}

orders_tracker/templates/modal.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Трекер_Замовлень</title>
    <link rel="stylesheet" href="/static/css/bulma.min.css"/>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/icon.png') }}">
    <script src="/static/ionicons/ionicons.esm.js" type="module"></script>
    <script nomodule src="/static/ionicons/ionicons.js"></script>

    <link rel="stylesheet" href="/static/jquery/jquery-ui.css">
    <script type="text/javascript" src="/static/jquery/jquery-latest.js"></script>
    <script src="/static/jquery/jquery-ui.js"></script>
</head>

<body>
<div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-content" style="width: 50%">
        <div class="block">
            <a class="button is-dark is-rounded" href="{{ return_link }}">
                <ion-icon name="return-down-back-outline"></ion-icon>
                <span style="padding-left: 10px;">Повернутися</span>
            </a>
        </div>

        <div class="message is-medium">
            <div class="message-header">
                {% block message_header %}
                {% endblock %}
            </div>
            <div class="message-body">
                {% block form %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

orders_tracker/templates/notification.html
{% with notifications = get_flashed_messages(with_categories=True) %}
    {% if notifications %}
        {%- for msg in notifications %}

            {% if msg[0] == "error" %}
                <div class="notification is-danger">
                    <button class="delete"></button>
                    <div class="level-left">
                        <div class="level-item">
                            <span><ion-icon size="large" name="alert-circle-outline"></ion-icon></span>
                        </div>
                        <div class="level-item">
                            <h6 class="subtitle is-6">{{ msg[1] }}</h6>
                        </div>
                    </div>
                </div>
            {% endif %}

            {% if msg[0] == "success" %}
                <div class="notification is-success">
                    <button class="delete"></button>
                    <div class="level-left">
                        <div class="level-item">
                            <span><ion-icon size="large" name="checkmark-circle-outline"></ion-icon></span>
                        </div>
                        <div class="level-item">
                            <h6 class="subtitle is-6">{{ msg[1] }}</h6>
                        </div>
                    </div>
                </div>
            {% endif %}

            {% if msg[0] == "warning" %}
                <div class="notification is-warning">
                    <button class="delete"></button>
                    <div class="level-left">
                        <div class="level-item">
                            <span><ion-icon size="large" name="warning-outline"></ion-icon></span>
                        </div>
                        <div class="level-item">
                            <h6 class="subtitle is-6">{{ msg[1] }}</h6>
                        </div>
                    </div>
                </div>
            {% endif %}

        {% endfor -%}
    {% endif %}
{% endwith %}

<script>
    document.addEventListener('DOMContentLoaded', () => {
        (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
            const $notification = $delete.parentNode;
            var div = document.createElement('div');
            div.className = 'level';


            $delete.addEventListener('click', () => {
                var parentNode = $notification.parentNode;
                parentNode.insertBefore(div, document.getElementById('workspace'));
                parentNode.removeChild($notification);
            });
        });
    });
</script>