orders_tracker/blueprints/staff/routes.py
from flask import Blueprint, render_template, request, redirect, url_for

from orders_tracker.blueprints.staff.service import render_empty, get_staff_orders_in_year
from orders_tracker.forms import NewStaffForm
from orders_tracker.models import Staff
from orders_tracker.blueprints.staff.service import get_staff_orders_in_month, get_staff_orders_in_previous_month, \
    add_staff
from orders_tracker.tables import StaffTable

staff_blueprint = Blueprint('staff_bp', __name__, template_folder="templates")


@staff_blueprint.route('/staff', methods=['GET', 'POST'])
def staff():
    staff_list = Staff.query.all()

    if len(staff_list) == 0:
        return render_empty()

    for worker in staff_list:
        setattr(worker, 'orders_prev_month', get_staff_orders_in_previous_month(worker))
        setattr(worker, 'orders_month', get_staff_orders_in_month(worker))
        setattr(worker, 'orders_year', get_staff_orders_in_year(worker))
    table = StaffTable(staff_list)

    return render_template('staff.html', table=table)


@staff_blueprint.route('/staff/new', methods=['GET', 'POST'])
def new_staff():
    start_page_arg = request.args.get('start')
    modal_form = NewStaffForm()

    if request.method == 'POST' and modal_form.validate_on_submit():
        created_staff = Staff(modal_form.name.data)
        add_staff(created_staff)

        if start_page_arg == '1':
            return redirect(url_for('start_bp.start'))

        return redirect(url_for('staff_bp.staff'))

    if start_page_arg == '1':
        return render_template('new_staff_modal.html',
                               modal_form=modal_form,
                               message_title="Створення нового працівника",
                               return_link=url_for('start_bp.start'))

    return render_template('new_staff_modal.html',
                           modal_form=modal_form,
                           message_title="Створення нового працівника")

orders_tracker/blueprints/staff/templates/new_staff_modal.html
{% extends 'modal.html' %}

{% if not return_link %}
    {% set return_link=url_for('staff_bp.staff') %}
{% endif %}

{% block message_header %}
    <div class="level-item">
        <p id="message_title">{{ message_title }}</p>
    </div>
    <div class="level-item is-hidden-mobile">
        <ion-icon size="large" name="add"></ion-icon>
    </div>
{% endblock %}

{% block form %}
    {% if get_flashed_messages(with_categories=True) %}
        {% include 'notification.html' %}
    {% endif %}

    <form action="" method="post" novalidate>
        {{ modal_form.hidden_tag() }}
        <div class="field">
            <div class="column">
                <div class="field">
                    <label class="label">{{ modal_form.name.label }}</label>
                    <p class="control">
                        {{ modal_form.name(class='input') }}
                    </p>
                </div>
            </div>
        </div>
        <br/>
        <div class="columns is-centered">
            <div class="column is-half">
                <div class="control has-icon-right">
                    {{ modal_form.submit(class='button is-link is-outlined is-rounded is-fullwidth') }}
                </div>
            </div>
        </div>
    </form>
{% endblock %}

orders_tracker/blueprints/staff/templates/staff.html
{% extends "message.html" %}

{% set pagination_source='staff_bp.staff' %}


{% block panel %}
    {% if get_flashed_messages(with_categories=True) %}
        {% include 'notification.html' %}
    {% else %}
        <div class="level"></div>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <nav class="breadcrumb pl-3">
        <ul>
            <li class="is-active">
                <a>
                    <ion-icon name="happy-outline"></ion-icon>
                    <span class="pl-2">Працівники</span>
                </a>
            </li>
            <li>
                <a href="">
                    <ion-icon name="list-outline"></ion-icon>
                    <span class="pl-2">Всі</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block message_header %}
    <ion-icon size="large" name="happy-outline"></ion-icon>
    <span class="pl-2">Список працівників</span>
{% endblock %}

{% block message_body %}
    <div class="table_div">
        {{ table|safe }}
    </div>

    <div class="block has-text-centered">
        <hr>
        <a class="button is-rounded is-success is-outlined"
           href="{{ url_for('staff_bp.new_staff') }}">
            <span>Додати працівника</span>
            <span class="icon"><ion-icon size="large" name="add"></ion-icon></span>
        </a>
    </div>

    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}