orders_tracker/blueprints/clients/routes.py
import urllib

from flask import Blueprint, request, render_template, flash, redirect, url_for

from orders_tracker.blueprints.clients.service import add_client, update_client, remove_client, search_clients, \
    get_form_fields, get_path_args, \
    get_clients_count, render_empty, get_pagination_metadata, paginate_clients
from orders_tracker.forms import NewClientForm, DeleteConfirmForm
from orders_tracker.models import Client, Device
from orders_tracker.tables import ClientsTable

clients_blueprint = Blueprint('clients_bp', __name__, template_folder="templates")


@clients_blueprint.route('/clients/new', methods=['GET', 'POST'])
def new_client():
    form = NewClientForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            created_client = Client(form.name.data, form.phone.data, form.address.data, form.notes.data)
            add_client(created_client)
            return redirect(url_for('clients_bp.clients'))
        else:
            flash('Перевірте введені значення.', category='warning')

    return render_template('new_client.html', form=form)


@clients_blueprint.route('/clients', methods=['GET', 'POST'])
def clients():
    if request.method == 'POST':
        search_field = get_form_fields()
        return redirect(url_for('clients_bp.clients',
                                search_query=search_field))

    search_arg, page_arg = get_path_args()

    stats = {'total': get_clients_count(), 'filter': -1}

    clients_query = search_clients(search_arg)

    stats['filter'] = clients_query.count()
    if stats['filter'] == 0:
        return render_empty(stats, search_arg)

    pagination_metadata = get_pagination_metadata(page_arg, clients_query)

    clients_list = paginate_clients(pagination_metadata, clients_query)
    table = ClientsTable(clients_list)

    return render_template('clients.html',
                           table=table,
                           stats=stats,
                           search_field_value=search_arg,
                           pagination_data=pagination_metadata)


@clients_blueprint.route('/clients/<client_id>', methods=['GET', 'POST'])
def client(client_id):
    address_link = None
    selected_client = Client.query.filter_by(id=client_id).first_or_404()
    if selected_client.address:
        address_link = "https://www.google.com/maps/search/?api=1&query=" + \
                       urllib.parse.quote_plus(selected_client.address)

    devices = Device.query.filter_by(client_id=client_id).all()

    return render_template('client.html',
                           client=selected_client,
                           devices=devices,
                           address_link=address_link)


@clients_blueprint.route('/clients/<client_id>/edit', methods=['GET', 'POST'])
def edit_client(client_id):
    edited_client = Client.query.filter_by(id=client_id).first()
    modal_form = NewClientForm()

    if request.method == 'POST':
        if modal_form.validate_on_submit():
            edited_client.name = modal_form.name.data.strip()
            edited_client.phone = modal_form.phone.data
            edited_client.address = modal_form.address.data
            edited_client.notes = modal_form.notes.data
            update_client(edited_client)
            return redirect(url_for('clients_bp.client', client_id=edited_client.id))
        else:
            flash('Дані про клієнта не оновлено.', category='warning')

    modal_form = NewClientForm(edited_client)
    return render_template('edit_client.html',
                           form=modal_form,
                           message_title="Редагування інформації про клієнта",
                           client_id=edited_client.id,
                           color="is-link")


@clients_blueprint.route('/clients/<client_id>/delete', methods=['GET', 'POST'])
def delete_client(client_id):
    deleted_client = Client.query.filter_by(id=client_id).first()
    form = DeleteConfirmForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            remove_client(deleted_client)
            return redirect(url_for('clients_bp.clients'))

    return render_template('delete_confirm.html',
                           form=form,
                           client_id=deleted_client.id,
                           message_title="Видалення клієнта",
                           message="Ви дійсно бажаєте видалити клієнта " + deleted_client.name + "?")

orders_tracker/blueprints/clients/templates/client.html
{% extends "message.html" %}

{% block panel %}
    {% if get_flashed_messages(with_categories=True) %}
        {% include 'notification.html' %}
    {% else %}
        <div class='level'></div>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <nav class="breadcrumb pl-4">
        <ul>
            <li class="is-active">
                <a>
                    <ion-icon name="people-outline"></ion-icon>
                    <span class="pl-2">Робота з клієнтами</span>
                </a>
            </li>
            <li>
                <a href="{{ url_for('clients_bp.clients') }}">
                    <ion-icon name="list-outline"></ion-icon>
                    <span class="pl-2">База клієнтів</span>
                </a>
            </li>
            <li>
                <a href="">
                    <ion-icon name="person-outline"></ion-icon>
                    <span class="pl-2">{{ client.name }}</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block message_header %}
    <ion-icon size="large" name="information-circle-outline"></ion-icon>
    <span class="pl-2">Інформація про клієнта</span>
{% endblock %}

{% block message_body %}
    <div class="tile is-ancestor">
        <div class="tile is-7 is-vertical is-parent">
            <div class="tile is-child box">
                <article class="media">
                    <figure class="media-left">
                        <p class="image is-64x64">
                            <ion-icon style="font-size:48px;" name="person-outline"></ion-icon>
                        </p>
                    </figure>
                    <div class="media-content">
                        <div class="content">
                            <h3 class="title is-3">{{ client.name }}</h3>
                            <ul>
                                <li>Номер телефону:
                                    <strong>{{ client.phone if client.phone else "(Не вказано)" }}</strong></li>
                                <li>Адреса:
                                    <a href="{{ address_link if address_link else "" }}">
                                        <strong>{{ client.address if client.address else "(Не вказано)" }}</strong>
                                    </a>
                                </li>
                                {% if client.notes %}
                                    <li>Нотатки: <strong>{{ client.notes }}</strong></li>
                                {% endif %}
                            </ul>
                        </div>

                    </div>
                </article>
            </div>
            <div class="tile is-child">
                <div class="level-right">
                    <p class="buttons">
                        <a class="button is-rounded is-success is-outlined"
                           href="{{ url_for('devices_bp.new_device', client_id=client.id) }}">
                            <span>Додати пристрій</span>
                            <span class="icon"><ion-icon name="print"></ion-icon></span>
                        </a>

                        <a class="button is-rounded is-link is-outlined"
                           href="{{ url_for('clients_bp.edit_client', client_id=client.id) }}">
                            <span>Редагувати</span>
                            <span class="icon"><ion-icon name="pencil-outline"></ion-icon></span>
                        </a>

                        <a class="button is-rounded is-danger is-outlined"
                           href="{{ url_for('clients_bp.delete_client', client_id=client.id) }}">
                            <span>Видалити</span>
                            <span class="icon"><ion-icon name="trash"></ion-icon></span>
                        </a>
                    </p>

                </div>
            </div>
        </div>
        <div class="tile is-parent">
            <div class="tile is-child box">
                <div class="column">
                    <div class="level-left">
                        <ion-icon size="large" name="print-outline"></ion-icon>
                        {% if devices %}
                            <span class="title is-5 pl-2">Зареєстровані пристрої:</span>
                        {% else %}
                            <span class="title is-5 has-text-grey pl-2">Немає зареєстрованих пристроїв</span>
                        {% endif %}
                    </div>
                    <div class="section">
                        {% if devices %}
                            <ol>
                                {% for device in devices %}
                                    <div class="block">
                                        <li class="subtitle is-6">
                                            <span>{{ device.name if device.name else "(Без назви)" }}</span>
                                            <span class="tag is-primary is-light is-medium is-rounded"><strong>{{ device.serial }}</strong></span>
                                            <a class="button is-small is-link is-inverted is-pulled-right"
                                               href="{{ url_for('devices_bp.edit_device', client_id=client.id, serial=device.serial) }}">
                                                <ion-icon name="create-outline"></ion-icon>
                                            </a>
                                        </li>

                                    </div>
                                {% endfor %}
                            </ol>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

orders_tracker/blueprints/clients/templates/clients.html
{% extends "message.html" %}

{% set pagination_source='clients_bp.clients' %}

{% set previous_link=url_for(
                        pagination_source,
                        page=pagination_data['previous'],
                        search_query=search_field_value if search_field_value else None) %}

{% set next_link=url_for(
                        pagination_source,
                        page=pagination_data['next'],
                        search_query=search_field_value if search_field_value else None) %}

{% set first_link=url_for(
                        pagination_source,
                        page=pagination_data['first'],
                        search_query=search_field_value if search_field_value else None) %}

{% set current_link=url_for(
                        pagination_source,
                        page=pagination_data['current'],
                        search_query=search_field_value if search_field_value else None) %}

{% set last_link=url_for(
                        pagination_source,
                        page=pagination_data['last'],
                        search_query=search_field_value if search_field_value else None) %}


{% block panel %}
    {% if get_flashed_messages(with_categories=True) %}
        {% include 'notification.html' %}
    {% else %}
        <div class="level"></div>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <nav class="breadcrumb pl-3">
        <ul>
            <li class="is-active">
                <a>
                    <ion-icon name="people-outline"></ion-icon>
                    <span class="pl-2">Робота з клієнтами</span>
                </a>
            </li>
            <li>
                <a href="">
                    <ion-icon name="list-outline"></ion-icon>
                    <span class="pl-2">База</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block message_header %}
    <ion-icon size="large" name="people-outline"></ion-icon>
    <span class="pl-2">База клієнтів</span>
{% endblock %}

{% block message_body %}
    <nav class="level">
        <div class="level-left">
            <div class="field">
                <label class="label">Введіть пошуковий запит</label>
                <div class="control">
                    <form autocomplete="off" method="post">
                        <div class="field has-addons">
                            <div class="control">
                                <input class="input" type="text" name="search_field" placeholder="Пошуковий запит"
                                       value="{{ search_field_value if search_field_value else ''}}">
                            </div>

                            <div class="control">
                                {% if search_field_value %}
                                    <a href="{{ url_for('clients_bp.clients') }}" class="button">
                                        Очистити
                                    </a>
                                {% endif %}
                            </div>
                            <div class="control">
                                <input type="submit" class="button is-link" value="Пошук">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="level-right">
            <div>
                {% if stats.filter >= 0 and stats.filter != stats.total %}
                    <p class="heading has-text-weight-bold is-size-7">
                        За вашим запитом знайдено
                        <span class="tag is-primary is-medium is-rounded ">{{ stats.filter }}</span>
                        клієнтів
                    </p>
                {% else %}
                    <p class="heading has-text-weight-bold is-size-7">Всього клієнтів: <span
                            class="tag is-info is-medium is-rounded ">{{ stats.total }}</span>
                    </p>
                {% endif %}

            </div>
        </div>
    </nav>

    <div class="table_div">
        {{ table|safe }}
    </div>

    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

orders_tracker/blueprints/clients/templates/edit_client.html
{% extends 'modal.html' %}

{% set return_link=url_for('clients_bp.client', client_id=client_id) %}


{% block message_header %}
    <div class="level-item">
        <p id="message_title">{{ message_title }}</p>
    </div>
    <div class="level-item is-hidden-mobile">
        <ion-icon size="large" name="create-outline"></ion-icon>
    </div>
{% endblock %}

{% block form %}
    {% if get_flashed_messages(with_categories=True) %}
        {% include 'notification.html' %}
    {% endif %}

    <form action="" method="post" autocomplete="none">
        {{ form.hidden_tag() }}
        <div class="field is-horizontal">
            <div class="column">
                <div class="field">
                    <label class="label">{{ form.name.label }}</label>
                    <p class="control is-expanded has-icons-left">
                                    <span class="icon is-left">
                                        <ion-icon name="person-outline"></ion-icon>
                                    </span>
                        {{ form.name(class='input') }}
                    </p>
                </div>
                <div class="field">
                    <label class="label">{{ form.phone.label }}</label>
                    <div class="control is-expanded has-icons-left">
                        {{ form.phone(class='input') }}
                        <span class="icon is-left">
                            <ion-icon name="call-outline"></ion-icon>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label">{{ form.address.label }}</label>
                    <p class="control is-expanded has-icons-left">
                        {{ form.address(class='input') }}
                        <span class="icon is-left">
                            <ion-icon name="location-outline"></ion-icon>
                        </span>
                    </p>
                </div>
            </div>

            <div class="column is-fullheight">
                <label class="label">{{ form.notes.label }}</label>
                <div class="control is-expanded has-icons-left">
                    <span class="icon is-left">
                        <ion-icon name="document-text-outline"></ion-icon>
                    </span>
                    {{ form.notes(class='textarea input', rows="9") }}
                </div>
            </div>
        </div>
        <br/>
        <div class="columns is-centered">
            <div class="column is-3">
                <div class="control has-icon-right">
                    {{ form.submit(class='button is-link is-outlined is-rounded is-fullwidth') }}
                </div>
            </div>
        </div>

    </form>

    <script>
        $(function () {
            $.ajax({
                url: '{{ url_for("api_bp.client_autocomplete") }}'
            }).done(function (data) {
                $('#client_autocomplete').autocomplete({
                    classes: {"ui-autocomplete": "highlight"},
                    source: data
                });
            });
        });

        $('.dp').datepicker({
            dateFormat: "dd.mm.yy",
            monthNames: ['Січень', 'Лютий', 'Березень', 'Квітень', 'Травень', 'Червень', 'Липень', 'Серпень', 'Вересень', 'Жовтень', 'Листопад', 'Грудень'],
            dayNamesMin: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            firstDay: 1
        });
    </script>
{% endblock %}

orders_tracker/blueprints/clients/templates/new_client.html
{% extends "message.html" %}

{% block panel %}
    {% if get_flashed_messages(with_categories=True) %}
        {% include 'notification.html' %}
    {% else %}
        <div class="level"></div>
    {% endif %}
{% endblock %}


{% block breadcrumbs %}
    <nav class="breadcrumb pl-3">
        <ul>
            <li class="is-active">
                <a>
                    <ion-icon name="people-outline"></ion-icon>
                    <span class="pl-2">Робота з клієнтами</span>
                </a>
            </li>
            <li>
                <a href="">
                    <ion-icon name="person-add-outline"></ion-icon>
                    <span class="pl-2">Додати нового</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block message_header %}
        <ion-icon size="large" name="person-add-outline"></ion-icon>
        <span class="pl-2">Створення клієнта</span>
{% endblock %}

{% block message_body %}
    <form action="" method="post" autocomplete="none">
        {{ form.hidden_tag() }}
        <div class="field is-horizontal">
            <div class="column">
                <div class="field">
                    <label class="label">{{ form.name.label }}</label>
                    <p class="control is-expanded has-icons-left">
                                    <span class="icon is-left">
                                        <ion-icon name="person-outline"></ion-icon>
                                    </span>
                        {{ form.name(class='input') }}
                    </p>
                </div>
                <div class="field">
                    <label class="label">{{ form.phone.label }}</label>
                    <div class="control is-expanded has-icons-left">
                        {{ form.phone(class='input') }}
                        <span class="icon is-left">
                                        <ion-icon name="call-outline"></ion-icon>
                                    </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label">{{ form.address.label }}</label>
                    <p class="control is-expanded has-icons-left">
                        {{ form.address(class='input') }}
                        <span class="icon is-left">
                                        <ion-icon name="location-outline"></ion-icon>
                                    </span>
                    </p>
                </div>
            </div>

            <div class="column is-fullheight">
                <label class="label">{{ form.notes.label }}</label>
                <div class="control is-expanded has-icons-left">
                                <span class="icon is-left">
                                    <ion-icon name="document-text-outline"></ion-icon>
                                </span>
                    {{ form.notes(class='textarea input', rows="7") }}
                </div>
            </div>
        </div>
        <br/>
        <br/>
        <div class="columns is-centered">
            <div class="column is-3">
                <div class="control has-icon-right">
                    {{ form.submit(class='button is-link is-light is-rounded is-fullwidth') }}
                </div>
            </div>
        </div>

    </form>

    <script>
        $(function () {
            $.ajax({
                url: '{{ url_for("api_bp.client_autocomplete") }}'
            }).done(function (data) {
                $('#client_autocomplete').autocomplete({
                    classes: {"ui-autocomplete": "highlight"},
                    source: data
                });
            });
        });

        $('.dp').datepicker({
            dateFormat: "dd.mm.yy",
            monthNames: ['Січень', 'Лютий', 'Березень', 'Квітень', 'Травень', 'Червень', 'Липень', 'Серпень', 'Вересень', 'Жовтень', 'Листопад', 'Грудень'],
            dayNamesMin: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            firstDay: 1
        });
    </script>
{% endblock %}